nums=[10,20,30,10,10]
print(nums)
nums.append(10)
print(nums)
print(nums.count(10))
nums_copy=nums.copy()
print(nums_copy)
# nums.clear()
# print(nums)
print(nums.index(30))
nums.insert(2,40)
print(nums)
nums.pop(2)
print(nums)
nums.remove(30)
print(nums)
nums.reverse()
print(nums)